version: "3.3"

services:
  db:
    image: postgres:12-alpine
    volumes:
      - postgres-data-12:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret

volumes:
  postgres-data-12:
